// Builds src/lib/shared/lucideIcons.js — the bundled icon table the `:icon:`
// element picks from: icon name → the inner markup of its <svg>.
//
// Read from the lucide-vue-next package the editor's own chrome already uses,
// so the icons a user can pick are exactly the set (and the version) the app
// ships. That package only exports Vue components — the path data is closed
// over — so this reads each icon module's node list as text. Nothing is
// evaluated, and every icon is run through the inline-SVG sanitizer: one that
// does not survive it whole fails the build rather than shipping half-drawn.
//
// The table is COMMITTED (like the runtime bundles), so a fresh clone needs no
// build step. Re-run after bumping lucide-vue-next:
//
//   npm run build:icons

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { lucideSvg } from '../src/lib/shared/svg.js'
import { CATALOG } from '../src/lib/catalog'
import type { CatalogNode } from '../src/lib/catalog'

const SOURCE = 'node_modules/lucide-vue-next/dist/esm/icons'
const TARGET = 'src/lib/shared/lucideIcons.js'
const CATALOG_TARGET = 'src/lib/catalog/icons.ts'

const ICON_RE = /createLucideIcon\("([a-z0-9-]+)",\s*\[([\s\S]*)\]\s*\);/
const NODE_RE = /\[\s*"([a-zA-Z]+)",\s*\{([^}]*)\}\s*\]/g
const ATTR_RE = /(?:"([^"]+)"|([A-Za-z][A-Za-z0-9]*))\s*:\s*"([^"]*)"/g

const version = JSON.parse(readFileSync('node_modules/lucide-vue-next/package.json', 'utf8'))
  .version as string

const icons: [string, string][] = []
for (const file of readdirSync(SOURCE).sort()) {
  if (!file.endsWith('.js') || file === 'index.js') continue
  const source = readFileSync(join(SOURCE, file), 'utf8')
  const icon = source.match(ICON_RE)
  if (!icon) throw new Error(`${file}: no icon definition found`)
  const name = icon[1]!

  let inner = ''
  let nodes = 0
  for (const node of icon[2]!.matchAll(NODE_RE)) {
    const attrs = [...node[2]!.matchAll(ATTR_RE)]
      .map((a) => [a[1] ?? a[2]!, a[3]!] as const)
      .filter(([key]) => key !== 'key')
      .map(([key, value]) => ` ${key}="${value}"`)
      .join('')
    inner += `<${node[1]}${attrs}/>`
    nodes++
  }
  if (!nodes) throw new Error(`${name}: no shapes found`)

  // the sanitizer is what every renderer trusts — an icon it would alter is
  // an icon that would not render as drawn
  const safe = lucideSvg(name, inner)
  const kept = safe.slice(safe.indexOf('>') + 1, safe.lastIndexOf('</svg>'))
  if (kept !== inner) throw new Error(`${name}: the sanitizer changed this icon\n  ${inner}\n  ${kept}`)
  icons.push([name, inner])
}

const body = icons.map(([name, inner]) => `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`).join('\n')
writeFileSync(
  TARGET,
  `// GENERATED by scripts/build-icons.ts from lucide-vue-next ${version} — do not edit.
// Re-run \`npm run build:icons\` after bumping the package.
//
// Icon name → the inner markup of its <svg>; wrap one with \`lucideSvg\`
// (./svg.js). Never import this statically from editor code: it is the whole
// icon set, and the picker loads it on demand.
//
// Lucide is ISC licensed — Copyright (c) for portions of Lucide are held by
// Cole Bemis 2013-2022 as part of Feather (MIT). All other copyright (c) for
// Lucide are held by Lucide Contributors 2022.
export const LUCIDE_VERSION = ${JSON.stringify(version)}
export const LUCIDE_ICONS = {
${body}
}
`,
)
console.log(`${icons.length} icons written to ${TARGET}`)

// --- the library's own subset ---
//
// A library entry names its icons, and turning one into a component has to be
// synchronous and cheap — it happens for every card on the components board.
// So the few icons the entries use are written out on their own, and the
// whole table stays something only the picker loads.
const table = new Map(icons)
const used = new Set<string>()
const collect = (node: CatalogNode) => {
  if (node.icon) used.add(node.icon)
  for (const part of Object.values(node.parts ?? {})) if (part.icon) used.add(part.icon)
  node.children?.forEach(collect)
}
for (const entry of CATALOG) collect(entry.root)

const subset = [...used].sort().map((name) => {
  const inner = table.get(name)
  if (!inner) throw new Error(`the library uses an icon that does not exist: "${name}"`)
  return `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`
})
writeFileSync(
  CATALOG_TARGET,
  `// GENERATED by scripts/build-icons.ts — do not edit.
// The bundled icons the LIBRARY's own entries use: a few dozen out of the whole
// set, so an entry can be materialized without loading all of it.
export const CATALOG_ICONS: Record<string, string> = {
${subset.join('\n')}
}
`,
)
console.log(`${subset.length} library icons written to ${CATALOG_TARGET}`)
