// GENERATED by scripts/build-icons.ts — do not edit.
// The bundled icons the LIBRARY's own entries use: a few dozen out of the whole
// set, so an entry can be materialized without loading all of it.
export const CATALOG_ICONS: Record<string, string> = {

}
